{% set name = "apache-airflow" %}
{% set version = "1.8.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e18e00d07c6c23c16c53bbfac87fc520e626119bb0123dca84076e83129ad4a3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - alembic >=0.8.3,<0.9
    - croniter >=0.3.8,<0.4
    - dill >=0.2.2,<0.3
    - flask >=0.11,<0.12
    - flask-admin ==1.4.1
    - flask-cache >=0.13.1,<0.14
    - flask-login ==0.2.11
    - flask-swagger ==0.2.13
    - flask-wtf ==0.14
    - funcsigs ==1.0.0
    - future >=0.15.0,<0.16
    - gitpython >=2.0.2
    - gunicorn >=19.3.0,<19.4.0
    - jinja2 >=2.7.3,<2.9.0
    - lxml >=3.6.0,<4.0
    - markdown >=2.5.2,<3.0
    - pandas >=0.17.1,<1.0.0
    - psutil >=4.2.0,<5.0.0
    - pygments >=2.0.1,<3.0
    - python-daemon >=2.1.1,<2.2
    - python-dateutil >=2.3,<3
    - python-nvd3 ==0.14.2
    - requests >=2.5.1,<3
    - setproctitle >=1.1.8,<2
    - sqlalchemy >=0.9.8
    - tabulate >=0.7.5,<0.8.0
    - thrift >=0.9.2,<0.10
    - zope.deprecation >=4.0,<5.0
  run:
    - python
    - alembic >=0.8.3,<0.9
    - croniter >=0.3.8,<0.4
    - dill >=0.2.2,<0.3
    - flask >=0.11,<0.12
    - flask-admin ==1.4.1
    - flask-cache >=0.13.1,<0.14
    - flask-login ==0.2.11
    - flask-swagger ==0.2.13
    - flask-wtf ==0.14
    - funcsigs ==1.0.0
    - future >=0.15.0,<0.16
    - gitpython >=2.0.2
    - gunicorn >=19.3.0,<19.4.0
    - jinja2 >=2.7.3,<2.9.0
    - lxml >=3.6.0,<4.0
    - markdown >=2.5.2,<3.0
    - pandas >=0.17.1,<1.0.0
    - psutil >=4.2.0,<5.0.0
    - pygments >=2.0.1,<3.0
    - python-daemon >=2.1.1,<2.2
    - python-dateutil >=2.3,<3
    - python-nvd3 ==0.14.2
    - requests >=2.5.1,<3
    - setproctitle >=1.1.8,<2
    - sqlalchemy >=0.9.8
    - tabulate >=0.7.5,<0.8.0
    - thrift >=0.9.2,<0.10
    - zope.deprecation >=4.0,<5.0

test:
  imports:
    - airflow
    - airflow.api
    - airflow.api.auth
    - airflow.api.auth.backend
    - airflow.api.client
    - airflow.api.common
    - airflow.api.common.experimental
    - airflow.bin
    - airflow.contrib
    - airflow.contrib.auth
    - airflow.contrib.auth.backends
    - airflow.contrib.executors
    - airflow.contrib.hooks
    - airflow.contrib.operators
    - airflow.contrib.sensors
    - airflow.contrib.task_runner
    - airflow.dag
    - airflow.example_dags
    - airflow.example_dags.subdags
    - airflow.executors
    - airflow.hooks
    - airflow.macros
    - airflow.migrations
    - airflow.migrations.versions
    - airflow.operators
    - airflow.security
    - airflow.task_runner
    - airflow.ti_deps
    - airflow.ti_deps.deps
    - airflow.utils
    - airflow.www
    - airflow.www.api
    - airflow.www.api.experimental
    - tests
    - tests.api
    - tests.api.client
    - tests.api.common
    - tests.contrib
    - tests.contrib.hooks
    - tests.contrib.operators
    - tests.contrib.sensors
    - tests.executors
    - tests.macros
    - tests.operators
    - tests.test_utils
    - tests.ti_deps
    - tests.ti_deps.contexts
    - tests.ti_deps.deps
    - tests.utils
    - tests.www
    - tests.www.api
    - tests.www.api.experimental

about:
  home: http://airflow.incubator.apache.org/
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: Programmatically author, schedule and monitor data pipelines
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
