{% set name = "functional" %}
{% set version = "0.7.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}

## C/Python version:
#{% set variant = "C" %}
#{% set url_inter = "41/30/74f9c23c1e726f55b0dd472374db5b2644bc5f74b143ca7afc3d188f4ef8" %}
#{% set hash_value = "6ac9b2d46ad05db90314928c8b4315634d62a774fb75b20843f7c0bff6e60112" %}

## Pure Python version, for the Windows build:
{% set variant = "Py" %}
{% set url_inter = "f5/5f/bb85f0ec7bc3d6b2e243ed223008d6d86b73c73e152358ab1fbc852b177d" %}
{% set hash_value = "9a7f2c9f9ced7c5ab058a63cd3d2643b8e66aadc3593303b2b1a5e2e711fbf8b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://files.pythonhosted.org/packages/{{ url_inter }}/{{ name }}-{{ variant }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - functional

about:
  home: http://oakwinter.com/code/functional/
  license: Python Software Foundation License
  license_family: OTHER
  license_file: ''
  summary: Tools for functional programming in python
  description: "functional provides Python users with numerous\r\ntools common in functional programming, such as foldl, foldr, flip, as well\r\nas mechanisms for partial function application and function\
    \ composition.\r\nfunctional also includes sane versions of the Python builtins map() and filter(),\r\nwritten without the weird semantics of the builtin versions.\r\n\r\nfunctional comes in two flavours:\
    \ one is written in a combination of C and\r\nPython, focusing on performance. The second is written in pure Python and\r\nemphasises code readability and portability. The pure-Python variant is also\r\
    \nrecommended if your setup does not allow compilation of third-party extension\r\nmodules."
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
