{% set name = "calysto_hy" %}
{% set version = "0.0.3" %}
{% set file_ext = "zip" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2ce2ba9985f8ac1bd6df6cc47f1700a2f2619a6c007545cad7b2a6f099a53903" %}
{% set git_hash = "c01f303a2bb03743e08f494e9a2f3efb6a87ab7a" %}

package:
  name: '{{ name|lower|replace("_", "-") }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/Calysto/{{ name }}/archive/{{ git_hash }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - noarch: python
    - setuptools
    - hy
    - metakernel
  run:
    - python
    - hy
    - metakernel

test:
  imports:
    - calysto_hy
    - calysto_hy.kernel

about:
  home: https://github.com/Calysto/Calysto_hy
  license: Modified BSD License
  license_family: BSD
  license_file: ''
  summary: A hy kernel for IPython
  description: |
    # Calysto Hy
    
    Calysto Hy is a Hy kernel for Jupyter based on [Metakernel](https://github.com/Calysto/metakernel). [Hy is a language](https://github.com/hylang/hy) that converts Lisp-like syntax to Python semantics. 
    
    This kernel is based on [bollwyvl/hy_kernel/](https://github.com/bollwyvl/hy_kernel/) That kernel treats Hy as a Python preprocessor, and can therefore use the standard IPython tools. Calysto Hy treats Hy as a full language. Because of this, it uses the MetaKernel to gain magics, shell, parallel processing, etc.
    
    ## Install
    
    ```shell
    pip3 install git+https://github.com/Calysto/calysto_hy.git
    python3 -m calysto_hy install
    ```
    If installing into the system, you may want to:
    
    ```shell
    sudo pip3 install git+https://github.com/Calysto/calysto_hy.git
    sudo python3 -m calysto_hy install
    ```
    
    Or into your personal space:
    
    ```shell
    pip3 install git+https://github.com/Calysto/calysto_hy.git --user
    python3 -m calysto_hy install --user
    ```
    
    Or into a virtualenv, when it is already activated:
    
    ```shell
    pip3 install git+https://github.com/Calysto/calysto_hy.git
    python3 -m calysto_hy install --sys-prefix
    ```
    
    ## Use
    
    ```shell
    jupyter console --kernel calysto_hy
    ```
    
    You can use Calysto Hy in Jupyter notebook by selecting the \"Calysto Hy\" kernel. See example [notebooks](https://github.com/Calysto/calysto_hy/tree/master/notebooks).

  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: 'gwerbin'
