{% set name = "edward" %}
{% set version = "1.3.4" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "10d6d7886235f4b9fa4ba401daef87c27937a04d2763f507643d730e51de37b6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - six >=1.10.0
  run:
    - python
    - numpy >=1.7
    - six >=1.10.0

test:
  imports:
    - edward
    - edward.criticisms
    - edward.inferences
    - edward.inferences.conjugacy
    - edward.models
    - edward.util
  requires:
    - pytest
    - pytest-pep8
    - tensorflow

about:
  home: http://edwardlib.org
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: A library for probabilistic modeling, inference, and criticism
  description: 'UNKNOWN



    '
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
